# Directory Pattern
actions:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

# Branch Pattern
fix:
  - head-branch: ['^fix/']

feature:
  - head-branch: ['^feature/']